<?php

namespace Database\Seeders;

use App\Models\Vehicle;
use Illuminate\Database\Seeder;

class VehicleSeeder extends Seeder
{
    public function run()
    {
        $vehicles = [
            [
                'name' => '海陸21号',
                'code' => '21',
                'number' => '4975',
                'capacity' => 20,
                'vehicle_type_id' => 1,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => '海陸22号',
                'code' => '22',
                'number' => '5672',
                'capacity' => 20,
                'vehicle_type_id' => 1,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => '海陸23号',
                'code' => '23',
                'number' => '5673',
                'capacity' => 20,
                'vehicle_type_id' => 1,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => '海陸24号',
                'code' => '24',
                'number' => '5674',
                'capacity' => 20,
                'vehicle_type_id' => 1,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => '海陸25号',
                'code' => '25',
                'number' => '5755',
                'capacity' => 20,
                'vehicle_type_id' => 1,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => '海陸26号',
                'code' => '26',
                'number' => '8478',
                'capacity' => 20,
                'vehicle_type_id' => 1,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => '海陸27号',
                'code' => '27',
                'number' => '8513',
                'capacity' => 20,
                'vehicle_type_id' => 1,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => '海陸28号',
                'code' => '28',
                'number' => '8514',
                'capacity' => 20,
                'vehicle_type_id' => 1,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => '海陸29号',
                'code' => '29',
                'number' => '205',
                'capacity' => 20,
                'vehicle_type_id' => 1,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => '海陸30号',
                'code' => '30',
                'number' => '1408',
                'capacity' => 20,
                'vehicle_type_id' => 1,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => '海陸31号',
                'code' => '31',
                'number' => '1409',
                'capacity' => 20,
                'vehicle_type_id' => 1,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => '海陸32号',
                'code' => '32',
                'number' => '1890',
                'capacity' => 20,
                'vehicle_type_id' => 1,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => '海陸33号',
                'code' => '33',
                'number' => '1891',
                'capacity' => 20,
                'vehicle_type_id' => 1,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => '奥村(1318)',
                'code' => null,
                'number' => '1318',
                'capacity' => null,
                'vehicle_type_id' => 5,
                'partner_id' => 2,
                'worker_id' => null,
            ],
            [
                'name' => '奥村(390)',
                'code' => null,
                'number' => '390',
                'capacity' => null,
                'vehicle_type_id' => 5,
                'partner_id' => 2,
                'worker_id' => null,
            ],
            [
                'name' => '奥村(1353)',
                'code' => null,
                'number' => '1353',
                'capacity' => null,
                'vehicle_type_id' => 5,
                'partner_id' => 2,
                'worker_id' => null,
            ],
            [
                'name' => '港湾(11号)',
                'code' => null,
                'number' => '11',
                'capacity' => null,
                'vehicle_type_id' => 5,
                'partner_id' => 3,
                'worker_id' => null,
            ],
            [
                'name' => '港湾(10号)',
                'code' => null,
                'number' => '10',
                'capacity' => null,
                'vehicle_type_id' => 5,
                'partner_id' => 3,
                'worker_id' => null,
            ],
            [
                'name' => '興洋(8498)',
                'code' => null,
                'number' => '8498',
                'capacity' => null,
                'vehicle_type_id' => 5,
                'partner_id' => 4,
                'worker_id' => null,
            ],
            [
                'name' => '興洋(8504)',
                'code' => null,
                'number' => '8504',
                'capacity' => null,
                'vehicle_type_id' => 5,
                'partner_id' => 4,
                'worker_id' => null,
            ],
            [
                'name' => '上組(8967)',
                'code' => null,
                'number' => '8967',
                'capacity' => null,
                'vehicle_type_id' => 5,
                'partner_id' => 5,
                'worker_id' => null,
            ],
            [
                'name' => '湯野(17)',
                'code' => null,
                'number' => '17',
                'capacity' => null,
                'vehicle_type_id' => 5,
                'partner_id' => 6,
                'worker_id' => null,
            ],
            [
                'name' => '海陸1号',
                'code' => '1',
                'number' => '1564',
                'capacity' => 15,
                'vehicle_type_id' => 2,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => '海陸2号',
                'code' => '2',
                'number' => '0000',
                'capacity' => 15,
                'vehicle_type_id' => 2,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => '海陸3号',
                'code' => '3',
                'number' => '6609',
                'capacity' => 15,
                'vehicle_type_id' => 2,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => '海陸5号',
                'code' => '5',
                'number' => '0000',
                'capacity' => 15,
                'vehicle_type_id' => 2,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => '海陸6号',
                'code' => '6',
                'number' => '6063',
                'capacity' => 15,
                'vehicle_type_id' => 2,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => '海陸7号',
                'code' => '7',
                'number' => '529',
                'capacity' => 15,
                'vehicle_type_id' => 2,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => '海陸8号',
                'code' => '8',
                'number' => '5115',
                'capacity' => 15,
                'vehicle_type_id' => 2,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => '海陸12号',
                'code' => '12',
                'number' => '5099',
                'capacity' => 15,
                'vehicle_type_id' => 2,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => 'キチナン(2112)',
                'code' => null,
                'number' => '2112',
                'capacity' => null,
                'vehicle_type_id' => 5,
                'partner_id' => 7,
                'worker_id' => null,
            ],
            [
                'name' => '富士1',
                'code' => null,
                'number' => '0000',
                'capacity' => null,
                'vehicle_type_id' => 5,
                'partner_id' => 8,
                'worker_id' => null,
            ],
            [
                'name' => '富士2',
                'code' => null,
                'number' => '0000',
                'capacity' => null,
                'vehicle_type_id' => 5,
                'partner_id' => 8,
                'worker_id' => null,
            ],
            [
                'name' => '富士3',
                'code' => null,
                'number' => '0000',
                'capacity' => null,
                'vehicle_type_id' => 5,
                'partner_id' => 8,
                'worker_id' => null,
            ],
            [
                'name' => null,
                'code' => 'A',
                'number' => '2939',
                'capacity' => null,
                'vehicle_type_id' => 3,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => null,
                'code' => 'B',
                'number' => '3029',
                'capacity' => null,
                'vehicle_type_id' => 3,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => null,
                'code' => 'C',
                'number' => '2776',
                'capacity' => null,
                'vehicle_type_id' => 3,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => null,
                'code' => 'D',
                'number' => '3043',
                'capacity' => null,
                'vehicle_type_id' => 3,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => null,
                'code' => 'E',
                'number' => '0000',
                'capacity' => null,
                'vehicle_type_id' => 3,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => null,
                'code' => 'F',
                'number' => '0000',
                'capacity' => null,
                'vehicle_type_id' => 3,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => null,
                'code' => null,
                'number' => '1629',
                'capacity' => null,
                'vehicle_type_id' => 3,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => null,
                'code' => null,
                'number' => '1789',
                'capacity' => null,
                'vehicle_type_id' => 3,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => null,
                'code' => 'G',
                'number' => '1565',
                'capacity' => null,
                'vehicle_type_id' => 3,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => null,
                'code' => 'H',
                'number' => '1566',
                'capacity' => null,
                'vehicle_type_id' => 3,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => null,
                'code' => 'I',
                'number' => '1670',
                'capacity' => null,
                'vehicle_type_id' => 3,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => null,
                'code' => 'J',
                'number' => '8415',
                'capacity' => null,
                'vehicle_type_id' => 3,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => null,
                'code' => 'L',
                'number' => '204',
                'capacity' => null,
                'vehicle_type_id' => 3,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => null,
                'code' => 'M',
                'number' => '1288',
                'capacity' => null,
                'vehicle_type_id' => 3,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => null,
                'code' => null,
                'number' => '7481',
                'capacity' => null,
                'vehicle_type_id' => 3,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [

                'name' => null,
                'code' => '6T',
                'number' => '6428',
                'capacity' => 6,
                'vehicle_type_id' => 4,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => null,
                'code' => '6T',
                'number' => '6428',
                'capacity' => 6,
                'vehicle_type_id' => 4,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => '出光(PKS)',
                'code' => 'P1',
                'number' => '9810',
                'capacity' => null,
                'vehicle_type_id' => 5,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => '出光(PKS)',
                'code' => 'P2',
                'number' => '9811',
                'capacity' => null,
                'vehicle_type_id' => 5,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => '出光(WP)',
                'code' => 'W1',
                'number' => '1417',
                'capacity' => null,
                'vehicle_type_id' => 5,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => '出光(WP)',
                'code' => 'W2',
                'number' => '1418',
                'capacity' => null,
                'vehicle_type_id' => 5,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => '軽バン2151',
                'code' => null,
                'number' => '0000',
                'capacity' => null,
                'vehicle_type_id' => 5,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => 'MiraE:S6008',
                'code' => null,
                'number' => '0000',
                'capacity' => null,
                'vehicle_type_id' => 5,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => '2t 1648',
                'code' => null,
                'number' => '0000',
                'capacity' => 2,
                'vehicle_type_id' => 5,
                'partner_id' => 1,
                'worker_id' => null,
            ],
        ];

        foreach ($vehicles as $vehicle) {
            Vehicle::create($vehicle);
        }
    }
}
