<?php

namespace Database\Seeders;

use App\Models\Vehicle;
use Illuminate\Database\Seeder;

class VehicleSeeder extends Seeder
{
    public function run()
    {
        $vehicles = [
            [
                'name' => '海陸（２１号）',
                'code' => '21',
                'number' => '4975',
                'capacity' => 20,
                'vehicle_type_id' => 1,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => '海陸（２２号）',
                'code' => '22',
                'number' => '5672',
                'capacity' => 20,
                'vehicle_type_id' => 1,
                'partner_id' => 1,
                'worker_id' => 1,
            ],
            [
                'name' => '海陸（２３号）',
                'code' => '23',
                'number' => '5673',
                'capacity' => 20,
                'vehicle_type_id' => 1,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => '海陸（２４号）',
                'code' => '24',
                'number' => '5674',
                'capacity' => 20,
                'vehicle_type_id' => 1,
                'partner_id' => 1,
                'worker_id' => 2,
            ],
            [
                'name' => '海陸（２５号）',
                'code' => '25',
                'number' => '5755',
                'capacity' => 20,
                'vehicle_type_id' => 1,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => '海陸（２６号）',
                'code' => '26',
                'number' => '8478',
                'capacity' => 20,
                'vehicle_type_id' => 1,
                'partner_id' => 1,
                'worker_id' => 3,
            ],
            [
                'name' => '海陸（２７号）',
                'code' => '27',
                'number' => '8513',
                'capacity' => 20,
                'vehicle_type_id' => 1,
                'partner_id' => 1,
                'worker_id' => 4,
            ],
            [
                'name' => '海陸（２８号）',
                'code' => '28',
                'number' => '8514',
                'capacity' => 20,
                'vehicle_type_id' => 1,
                'partner_id' => 1,
                'worker_id' => 5,
            ],
            [
                'name' => '海陸（２９号）',
                'code' => '29',
                'number' => '205',
                'capacity' => 20,
                'vehicle_type_id' => 1,
                'partner_id' => 1,
                'worker_id' => 6,
            ],
            [
                'name' => '海陸（３０号）',
                'code' => '30',
                'number' => '1408',
                'capacity' => 20,
                'vehicle_type_id' => 1,
                'partner_id' => 1,
                'worker_id' => 7,
            ],
            [
                'name' => '海陸（３１号）',
                'code' => '31',
                'number' => '1409',
                'capacity' => 20,
                'vehicle_type_id' => 1,
                'partner_id' => 1,
                'worker_id' => 8,
            ],
            [
                'name' => '海陸（３２号）',
                'code' => '32',
                'number' => '1890',
                'capacity' => 20,
                'vehicle_type_id' => 1,
                'partner_id' => 1,
                'worker_id' => 9,
            ],
            [
                'name' => '海陸（３３号）',
                'code' => '33',
                'number' => '1891',
                'capacity' => 20,
                'vehicle_type_id' => 1,
                'partner_id' => 1,
                'worker_id' => 10,
            ],
            [
                'name' => '奥村（１３１８）',
                'code' => null,
                'number' => '1318',
                'capacity' => null,
                'vehicle_type_id' => 5,
                'partner_id' => 2,
                'worker_id' => null,
            ],
            [
                'name' => '奥村（３９０）',
                'code' => null,
                'number' => '390',
                'capacity' => null,
                'vehicle_type_id' => 5,
                'partner_id' => 2,
                'worker_id' => null,
            ],
            [
                'name' => '奥村（１３５３）',
                'code' => null,
                'number' => '1353',
                'capacity' => null,
                'vehicle_type_id' => 5,
                'partner_id' => 2,
                'worker_id' => null,
            ],
            [
                'name' => '港湾（１１号）',
                'code' => null,
                'number' => '11',
                'capacity' => null,
                'vehicle_type_id' => 5,
                'partner_id' => 3,
                'worker_id' => null,
            ],
            [
                'name' => '港湾（１０号）',
                'code' => null,
                'number' => '10',
                'capacity' => null,
                'vehicle_type_id' => 5,
                'partner_id' => 3,
                'worker_id' => null,
            ],
            [
                'name' => '興洋（８４９８）',
                'code' => null,
                'number' => '8498',
                'capacity' => null,
                'vehicle_type_id' => 5,
                'partner_id' => 4,
                'worker_id' => null,
            ],
            [
                'name' => '興洋（８５０４）',
                'code' => null,
                'number' => '8504',
                'capacity' => null,
                'vehicle_type_id' => 5,
                'partner_id' => 4,
                'worker_id' => null,
            ],
            [
                'name' => '上組（８９６７）',
                'code' => null,
                'number' => '8967',
                'capacity' => null,
                'vehicle_type_id' => 5,
                'partner_id' => 5,
                'worker_id' => null,
            ],
            [
                'name' => '湯野（１７）',
                'code' => null,
                'number' => '17',
                'capacity' => null,
                'vehicle_type_id' => 5,
                'partner_id' => 6,
                'worker_id' => null,
            ],
            [
                'name' => '海陸（１号）',
                'code' => '1',
                'number' => '1564',
                'capacity' => 15,
                'vehicle_type_id' => 2,
                'partner_id' => 1,
                'worker_id' => 11,
            ],
            [
                'name' => '海陸（２号）',
                'code' => '2',
                'number' => '0000',
                'capacity' => 15,
                'vehicle_type_id' => 2,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => '海陸（３号）',
                'code' => '3',
                'number' => '6609',
                'capacity' => 15,
                'vehicle_type_id' => 2,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => '海陸（５号）',
                'code' => '5',
                'number' => '0000',
                'capacity' => 15,
                'vehicle_type_id' => 2,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => '海陸（６号）',
                'code' => '6',
                'number' => '6063',
                'capacity' => 15,
                'vehicle_type_id' => 2,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => '海陸（７号）',
                'code' => '7',
                'number' => '529',
                'capacity' => 15,
                'vehicle_type_id' => 2,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => '海陸（８号）',
                'code' => '8',
                'number' => '5115',
                'capacity' => 15,
                'vehicle_type_id' => 2,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => '海陸（１２号）',
                'code' => '12',
                'number' => '5099',
                'capacity' => 15,
                'vehicle_type_id' => 2,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => 'キチナン（２１１２）',
                'code' => null,
                'number' => '2112',
                'capacity' => null,
                'vehicle_type_id' => 5,
                'partner_id' => 7,
                'worker_id' => null,
            ],
            [
                'name' => '富士１',
                'code' => null,
                'number' => '0000',
                'capacity' => null,
                'vehicle_type_id' => 5,
                'partner_id' => 8,
                'worker_id' => null,
            ],
            [
                'name' => '富士２',
                'code' => null,
                'number' => '0000',
                'capacity' => null,
                'vehicle_type_id' => 5,
                'partner_id' => 8,
                'worker_id' => null,
            ],
            [
                'name' => '富士３',
                'code' => null,
                'number' => '0000',
                'capacity' => null,
                'vehicle_type_id' => 5,
                'partner_id' => 8,
                'worker_id' => null,
            ],
            [
                'name' => null,
                'code' => 'A',
                'number' => '2939',
                'capacity' => null,
                'vehicle_type_id' => 3,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => null,
                'code' => 'B',
                'number' => '3029',
                'capacity' => null,
                'vehicle_type_id' => 3,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => null,
                'code' => 'C',
                'number' => '2776',
                'capacity' => null,
                'vehicle_type_id' => 3,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => null,
                'code' => 'D',
                'number' => '3043',
                'capacity' => null,
                'vehicle_type_id' => 3,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => null,
                'code' => 'E',
                'number' => '0000',
                'capacity' => null,
                'vehicle_type_id' => 3,
                'partner_id' => 1,
                'worker_id' => 16,
            ],
            [
                'name' => null,
                'code' => 'F',
                'number' => '0000',
                'capacity' => null,
                'vehicle_type_id' => 3,
                'partner_id' => 1,
                'worker_id' => 17,
            ],
            [
                'name' => null,
                'code' => null,
                'number' => '1629',
                'capacity' => null,
                'vehicle_type_id' => 3,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => null,
                'code' => null,
                'number' => '1789',
                'capacity' => null,
                'vehicle_type_id' => 3,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => null,
                'code' => 'G',
                'number' => '1565',
                'capacity' => null,
                'vehicle_type_id' => 3,
                'partner_id' => 1,
                'worker_id' => 12,
            ],
            [
                'name' => null,
                'code' => 'H',
                'number' => '1566',
                'capacity' => null,
                'vehicle_type_id' => 3,
                'partner_id' => 1,
                'worker_id' => 13,
            ],
            [
                'name' => null,
                'code' => 'I',
                'number' => '1670',
                'capacity' => null,
                'vehicle_type_id' => 3,
                'partner_id' => 1,
                'worker_id' => 14,
            ],
            [
                'name' => null,
                'code' => 'J',
                'number' => '8415',
                'capacity' => null,
                'vehicle_type_id' => 3,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => null,
                'code' => 'L',
                'number' => '204',
                'capacity' => null,
                'vehicle_type_id' => 3,
                'partner_id' => 1,
                'worker_id' => 15,
            ],
            [
                'name' => null,
                'code' => 'M',
                'number' => '1288',
                'capacity' => null,
                'vehicle_type_id' => 3,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => null,
                'code' => null,
                'number' => '7481',
                'capacity' => null,
                'vehicle_type_id' => 3,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => null,
                'code' => '6T',
                'number' => '6428',
                'capacity' => 6,
                'vehicle_type_id' => 4,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => '出光(PKS)',
                'code' => 'P1',
                'number' => '9810',
                'capacity' => null,
                'vehicle_type_id' => 5,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => '出光(PKS)',
                'code' => 'P2',
                'number' => '9811',
                'capacity' => null,
                'vehicle_type_id' => 5,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => '出光(WP)',
                'code' => 'W1',
                'number' => '1417',
                'capacity' => null,
                'vehicle_type_id' => 5,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => '出光(WP)',
                'code' => 'W2',
                'number' => '1418',
                'capacity' => null,
                'vehicle_type_id' => 5,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => '軽バン2151',
                'code' => null,
                'number' => '0000',
                'capacity' => null,
                'vehicle_type_id' => 5,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => 'MiraE:S6008',
                'code' => null,
                'number' => '0000',
                'capacity' => null,
                'vehicle_type_id' => 5,
                'partner_id' => 1,
                'worker_id' => null,
            ],
            [
                'name' => '2t 1648',
                'code' => null,
                'number' => '0000',
                'capacity' => 2,
                'vehicle_type_id' => 5,
                'partner_id' => 1,
                'worker_id' => null,
            ],
        ];
        
        
        foreach ($vehicles as $vehicle) {
            Vehicle::create($vehicle);
        }
    }
}
